# Use root/example as user/password credentials
# docker-compose -f docker-compose.yml up -d
version: '3.9'

services:
  mongo:
    container_name: mongo_inventory
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "labsit"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin123"
    ports:
      - "27017:27017"
    volumes:
      - ../mongo/inventory/data/configdb:/data/configdb
      - ../mongo/inventory/data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    extra_hosts:
      - "host.docker.internal:172.4.0.1"

  mongo-express:
    container_name: mongo_express_order
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongo:27017/
    extra_hosts:
      - "host.docker.internal:172.4.0.1"

  invetory-manager:
    image: inventory_manager:1.0.4
    build: .
    container_name: inventory_manager
    environment:
      - MONGO_DATA_BASE_URL=mongodb://admin:admin123@mongo:27017
      - PORT_SERVER=1323
    ports:
      - "8985:1323"
    depends_on:
      - mongo
    restart: always
    extra_hosts:
      - "host.docker.internal:172.4.0.1"

volumes:
  pgdata: